# Required Env Vars
# NPM_TOKEN

# Main Config
version: 2.1
# reusable environment for all jobs
executors:
  main-executor:
    working_directory: ~/webex-js-sdk
    docker:
      - image: circleci/node:carbon-browsers

commands:
  install_graphicsmagick_and_libgcrypt:
    description: 'Install graphicsmagick and libgcrypt'
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install graphicsmagick libgcrypt-dev -y
  checkout_and_fetch:
    description: 'Checkout and fetch tags'
    steps:
      - checkout
      - run: git remote add upstream git@github.com:webex/webex-js-sdk.git
      - run: git fetch upstream --tags
  restore_node_modules:
    description: 'Restore the node_modules dependencies cache'
    steps:
      - restore_cache:
          keys:
            - node-module-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-module-cache-v1-{{ .Branch }}-
            - node-module-cache-v1-
  restore_built_packages:
    description: 'Restore built packages'
    steps:
      - attach_workspace:
          at: ~/webex-js-sdk
  skip_check:
    description: 'Check to see if testing needs to be skipped'
    steps:
      - run:
          name: Check if we need to skip
          command: if [[ -z $(node tooling/modified-packages.js) ]]; then circleci step halt; fi

# Main Config
jobs:
  npm_install:
    executor: main-executor
    environment:
      SAUCE_CONNECT_DOWNLOAD_ON_INSTALL: true
    steps:
      - install_graphicsmagick_and_libgcrypt
      - checkout_and_fetch
      - run:
          name: 'Update NPM and Install dependencies'
          command: sudo npm install -g npm@6
      - run:
          name: 'Install dependencies'
          command: npm ci
      - save_cache:
          key: node-module-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/usr/local/lib/node_modules
            - node_modules
      - run:
          name: 'Save NPM install log'
          command: npm ls --json > /tmp/npm_install.log || true
      - store_artifacts:
          path: /tmp/npm_install.log
          destination: npm-install

  build:
    executor: main-executor
    environment:
      NODE_ENV: 'test'
    steps:
      - install_graphicsmagick_and_libgcrypt
      - checkout_and_fetch
      - restore_node_modules
      - run:
          name: 'Build all packages'
          command: npm run build
      - persist_to_workspace:
          root: ~/webex-js-sdk
          paths:
            - packages/node_modules

  static_analysis:
    executor: main-executor
    steps:
      - checkout_and_fetch
      - restore_node_modules
      - restore_built_packages
      - run:
          name: 'Run ESLint'
          command: npm run lint:ci
      - store_test_results:
          path: reports/style
      - store_artifacts:
          path: reports/style
          destination: style

  unit_tests:
    executor: main-executor
    environment:
      COVERAGE: true
    steps:
      - checkout_and_fetch
      - restore_node_modules
      - restore_built_packages
      - skip_check
      - run:
          name: 'Generate Build Number'
          command: echo "export BUILD_NUMBER=CircleCI-${CIRCLE_PR_USERNAME}-${CIRCLE_PR_REPONAME}-${CIRCLE_PR_NUMBER}_${CIRCLE_WORKFLOW_ID}" >> $BASH_ENV
      - run:
          name: 'Test modified packages'
          command: npm run test:ci:github
      - run:
          name: 'Check if any unit tests failed'
          command: |
            failures=$(find reports -iname 'webex*.xml' -print0 | xargs -0 sed -n 's/.*failures=\"\([^\"]*\).*/\1/p' | xargs)
            errors=$(find reports -iname 'webex*.xml' -print0 | xargs -0 sed -n 's/.*errors=\"\([^\"]*\).*/\1/p' | xargs)

            echo Failures $failures
            echo Errors $errors

            if [[ "$failures" -ne *0* ]] || [[ "$errors" -ne *0* ]]; then
              echo 'Unit tests failed'
              exit 1
            fi
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/junit
          destination: junit

  samples:
    executor: main-executor
    environment:
      NODE_ENV: 'test'
      COVERAGE: true
    steps:
      - checkout_and_fetch
      - restore_node_modules
      - restore_built_packages
      - run:
          name: 'Generate Build Number'
          command: echo "export BUILD_NUMBER=CircleCI-${CIRCLE_PR_USERNAME}-${CIRCLE_PR_REPONAME}-${CIRCLE_PR_NUMBER}_${CIRCLE_WORKFLOW_ID}" >> $BASH_ENV
      - run:
          name: 'Test samples'
          command: npm run samples:test
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/junit/wdio
          destination: wdio
      - store_artifacts:
          path: reports/cobertura.xml
          destination: cobertura.xml
      - store_artifacts:
          path: /home/circleci/.npm/_logs/
          destination: npm-logs

  integration_tests:
    executor: main-executor
    environment:
      COVERAGE: true
    steps:
      - install_graphicsmagick_and_libgcrypt
      - checkout_and_fetch
      - restore_node_modules
      - restore_built_packages
      - skip_check
      - run:
          name: 'Generate Build Number'
          command: echo "export BUILD_NUMBER=CircleCI-${CIRCLE_PR_USERNAME}-${CIRCLE_PR_REPONAME}-${CIRCLE_PR_NUMBER}_${CIRCLE_WORKFLOW_ID}" >> $BASH_ENV
      - run:
          name: 'Run all integration tests on Mac and Windows version of Chrome and Firefox'
          command: npm run test:ci:integration
      - run:
          name: 'Check if any integration tests failed'
          command: |
            failures=$(find reports -iname 'webex*.xml' -print0 | xargs -0 sed -n 's/.*failures=\"\([^\"]*\).*/\1/p' | xargs)
            errors=$(find reports -iname 'webex*.xml' -print0 | xargs -0 sed -n 's/.*errors=\"\([^\"]*\).*/\1/p' | xargs)

            echo Failures $failures
            echo Errors $errors

            if [[ "$failures" -ne *0* ]] || [[ "$errors" -ne *0* ]]; then
              echo 'Unit tests failed'
              exit 1
            fi
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/junit
          destination: junit

  bump_version:
    executor: main-executor
    steps:
      - checkout_and_fetch
      - restore_node_modules
      - restore_built_packages
      - skip_check
      - run:
          name: 'Generate Version Number'
          command: echo "export VERSION=$(npm run --silent get-next-version | xargs)" >> $BASH_ENV
      - run: echo ${VERSION}
      - run:
          name: 'Build Packages'
          command: npm run build
      - run:
          name: 'Build UMD script'
          command: npm run build:script -- --versionNumber=${VERSION}
      - run:
          name: 'Build Docs'
          command: npm run build:docs
      - run:
          name: 'Bump all package version'
          command: npm run tooling -- version set ${version} --all

  npm_publish:
    executor: main-executor
    steps:
      - checkout_and_fetch
      - restore_node_modules
      - restore_built_packages
      - run:
          name: 'Publish to NPM'
          command: npm run tooling -- exec -- bash -c 'npm publish --access public || true'

workflows:
  version: 2
  github_checks:
    jobs:
      - npm_install
      - build:
          requires:
            - npm_install
      - static_analysis:
          requires:
            - npm_install
      - unit_tests:
          requires:
            - build
            - static_analysis
      - samples:
          requires:
            - build
            - static_analysis
      - integration_tests:
          requires:
            - unit_tests
            - samples
          type: approval
  build_for_release:
    jobs:
      - npm_install:
          filters:
              branches:
                only: master
      - bump_version:
          filters:
            branches:
              only: master
          requires:
              - npm_install
          type: approval
  publish:
    jobs:
      - npm_install:
          filters:
              branches:
                only: master
              tags:
                only: /^v.*/
      - npm_publish:
          type: approval
          filters:
              branches:
                only: master
              tags:
                only: /^v.*/
